### ISSUE TITLE
Duration floating point round-off causes "IndexError: list index out of range" in write_videofile

### ISSUE THREAD

**Issue by pkarp0** [Zulko/moviepy#646]
The sample code creates a color clip with a duration of 2.24, a size of [1080, 1080] and fps=50.0
The clip writes properly after CompositeVideoClip but if it is concatenated then the duration changes slightly and writing fails.

```
>>> vclip = ColorClip([1080, 1080], color=[255, 128, 64], duration=2.24)
>>> vclip.duration
2.24
>>> vclip.size
(1080, 1080)
>>> comp = CompositeVideoClip([vclip])
>>> comp = comp.set_fps(50.0)
>>> comp.fps
50.0
>>> comp.write_videofile('comp.mp4', preset='ultrafast')
```
The file writes successfully

```
>>> concat = concatenate([comp])
>>> concat.duration
2.2400000000000002
>>> concat.write_videofile('concat.mp4', preset='ultrafast')
```

The write_videofile() fails with IndexError
```
  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-51>", line 2, in write_videofile
  File "/usr/local/lib/python3.6/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-50>", line 2, in write_videofile
  File "/usr/local/lib/python3.6/site-packages/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-49>", line 2, in write_videofile
  File "/usr/local/lib/python3.6/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.6/site-packages/moviepy/video/VideoClip.py", line 349, in write_videofile
    progress_bar=progress_bar)
  File "/usr/local/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_writer.py", line 209, in ffmpeg_write_video
    fps=fps, dtype="uint8"):
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 833, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/site-packages/moviepy/Clip.py", line 475, in generator
    frame = self.get_frame(t)
  File "<decorator-gen-14>", line 2, in get_frame
  File "/usr/local/lib/python3.6/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/lib/python3.6/site-packages/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/usr/local/lib/python3.6/site-packages/moviepy/video/compositing/concatenate.py", line 83, in make_frame
    return clips[i].get_frame(t - tt[i])
IndexError: list index out of range
```

**Comment by tburrows13** [comment]
Can confirm this problem, thanks for spotting!

**Comment by pkarp0** [comment]
@tburrows13 Who are you asking for confirmation?

**Comment by tburrows13** [comment]
I meant that I can confirm this problem, sorry!

**Comment by pkarp0** [comment]
@tburrows13 Great. Thanks for your help.

**Comment by AidasLiaudanskas** [comment]
Can confirm this is still happening. the output of concatenate_videoclips assumes there's one more frame than there are in the clips that were merged. Seems to happen because of the float precision when the time of certain clip cannot be represented exactly.

**Comment by AidasLiaudanskas** [comment]
Temporary workaround if anyone's still stuck:

```
    final_clip = concatenate_videoclips(list_of_clips)
    try:
        final_clip.write_videofile(save_path,  threads=6, logger=None)
        logger.info("Saved .mp4 without Exception at {}".format(save_path))
    except IndexError:
        # Short by one frame, so get rid on the last frame:
        final_clip = final_clip.subclip(t_end=(clip.duration - 1.0/final_clip.fps))
        final_clip.write_videofile(save_path, threads=6, logger=None)
        logger.info("Saved .mp4 after Exception at {}".format(save_path))
    except Exception as e:
        logger.warning("Exception {} was raised!!".format(e))  
```

**Comment by Ierezell** [comment]
Still get the same `IndexError` problem but the @AidasLiaudanskas patch works perfectly fine ! Thanks

**Comment by sunilk-n** [comment]
I'm still getting this issue now... Could you please look into this?

**Comment by sunilk-n** [comment]
I'm still getting this issue now... Could you please look into this?

**Comment by sunilk-n** [comment]
I'm still getting this issue now... Could you please look into this?

**Comment by Ethan0625** [comment]
> I'm still getting this issue now... Could you please look into this?

I fixed this issue in manually.

There is a prbloem in File concatenate.py, line 66

`timings =  np.cumsum([0] + [clip.duration for clip in clips]`

'clip.duration' is not always an integer.

so if you change 'clip.duration' to integer thing, that problem will solve.

But I don't know this solution make another problem.

**Comment by tbermudez10** [comment]
Hello, I am still having issues with this, ehile using the latest version (v1.0.3) and the patch suggested before 

(    final_clip = concatenate_videoclips(list_of_clips)
    try:
        final_clip.write_videofile(save_path,  threads=6, logger=None)
        logger.info("Saved .mp4 without Exception at {}".format(save_path))
    except IndexError:
        # Short by one frame, so get rid on the last frame:
        final_clip = final_clip.subclip(t_end=(clip.duration - 1.0/final_clip.fps))
        final_clip.write_videofile(save_path, threads=6, logger=None)
        logger.info("Saved .mp4 after Exception at {}".format(save_path))
    except Exception as e:
        logger.warning("Exception {} was raised!!".format(e))  )

Any news on how it will / can be fixed?

**Comment by LindaLawton** [comment]
I just posted a question on Stack overflow [write_videofile throws list index out of range - but works](https://stackoverflow.com/q/78340115/1841839)  I am wondering if it may be related to this 


I have a bunch of videos in a directory  1.mp4, 2.mp4 .... I am merging them into output_1_2.mp4.

The following code works, but ..

Its throwning an error that i cant seem to figure out.

>Merging: videos/1.mp4 videos/2.mp4 videos/output_1_2.mp4<br>
Length of clips list: 2<br>
Moviepy - Building video videos/output_1_2.mp4.<br>
MoviePy - Writing audio in output_1_2TEMP_MPY_wvf_snd.mp3<br>
t:   0%|          | 0/499 [00:00<?, ?it/s, now=None]MoviePy - Done.<br>
Moviepy - Writing video videos/output_1_2.mp4<br>
Error writing final clip: list index out of range<br>

Again it works the files are merged, im just trying to understand the why 

    final_clip.write_videofile(output_path, codec='libx264')

is throwing an **list index out of range** error.

As the code works i can probably just ignore it.  This question is more out of curiosity.



# Code

    import os
    import re
    
    from moviepy.editor import VideoFileClip, concatenate_videoclips
    
    
    def merge_videos_in_directory(directory):
        # Get a list of all files in the directory
        files = os.listdir(directory)
    
        # Filter out files that start with "output"
        files = [file for file in files if not file.startswith("output")]
    
        # Sort the files based on numeric part in the filename
        files.sort(key=lambda x: int(re.search(r'\d+', x).group()))
    
        # Print the list of files for debugging
        print("Files in directory:", files)
    
        # Iterate through the files in pairs
        for i in range(0, len(files), 2):
            # Check if there are at least two files remaining
            if i + 1 < len(files):
                # Get the paths of the two videos to merge
                video1_path = os.path.join(directory, files[i])
                video2_path = os.path.join(directory, files[i + 1])
    
                # Create the output file name
                output_name = f"output_{files[i][:-4]}_{files[i + 1][:-4]}.mp4"
                output_path = os.path.join(directory, output_name)
    
                # Merge the two videos
                print("Merging:", video1_path, video2_path, output_path)
                try:
                    merge_videos(video1_path, video2_path, output_path)
                except Exception as e:
                    print("Error merging videos:", e)
    
    
    def merge_videos(video1_path, video2_path, output_path):
        # Load the video clips
        video1 = VideoFileClip(video1_path)
        video2 = VideoFileClip(video2_path)
    
        # Print the lengths of the clips list for debugging
        print("Length of clips list:", len([video1, video2]))
    
        # Concatenate the video clips
        final_clip = concatenate_videoclips([video1, video2])
    
        try:
            # Write the final clip to a file
            final_clip.write_videofile(output_path, codec='libx264')  # exception thrown here.
    
        except Exception as e:
            # Handle any errors
            print("Error writing final clip:", e)
            # Close the clips if an error occurs
            final_clip.close()
            video1.close()
            video2.close()
        finally:
            # Close the clips
            final_clip.close()
            video1.close()
            video2.close()
    
    
    # Example usage:
    videos_dir = "videos/"
    merge_videos_in_directory(videos_dir)

**Comment by Implosiv3** [comment]
I see this as Closed, but it is still happening. I had this issue a few moments ago and I realized the error.

I concatenated some clips and obtained a duration of 8.116666666666667 when printed. If I apply the % operand the result is not 0 so, as it is detecting a value greater than the expected (maybe 8,1166666666666666666666666666667, just did it in my calculator app), it goes to the next frame that doesn't exist and fails.

I saw a workaround that seems to be working, but it is actually writing twice (one when it fails and the second one when fixed). I think this code below is faster and easier (`clip` here below is the result obtained when `concatenate_videoclips(...)` is executed):

`clip = clip.subclip(0, clip.duration // (1 / clip.fps) * (1 / clip.fps))`

You subclip it to the exact time moment which is accepted and points to the real last frame, so it won't fail on the first attempt.

**Comment by AtinChing** [comment]
Bumping this issue to bring more attention to it. 
Going to try @Implosiv3 's solution on moviepy 2.x and leave an update here (seems like his code is from moviepy 1.x because of subclip instead of subclipped)

**Comment by AtinChing** [comment]
@Implosiv3 's didn't work, not clear what the difference between clip and new_clip is in his code.
But his code intends to remove 1 frame, and my issue was that I got this error around 40-ish frames before the last frame. So i subclipped my CompositeVideoClip, and made its duration very slightly shorter (set the end time to floor of the current end time to 2 decimal digits, works just fine)

**Comment by Implosiv3** [comment]
Hello all, and @AtinChing. It's been a long time since this, but I would like to share something I've been facing.

When I load video files with the new version of moviepy and try to use it and write it, sometimes there is a warning that says that some frames were not able to be read and the last readable were used. I don't know if that is the problem we are talking/facing here, but I am experiencing it and I built a temporary solution.

Basically, I made a custom method in which I load the video, I calculate all the video time frame moments (according to the video fps and duration, and adding a very small decimal amount to each of them to avoid decimal errors). Now I iterate, starting from the last one, and I do a `get_frame(t)` (wrapped in a try-except), and when I find the first one that is ok, I recalculate the valid video duration, based on that last frame valid time moment, and set it as the new video duration, and then I start working with it like if nothing happened.

If you've used a Composite, maybe because of the start_time this is happening to you, but I don't know. Just wanted to share it.

**Comment by AtinChing** [comment]
@Implosiv3 
Hi Implosiv3, the issue im talking about is different to the on youve mentioned. You'll get a quick gist if you look at the errors everyone pasted in this thread. "Some frames were not able to be read, using last valid frame instead" is [#1233](https://github.com/Zulko/moviepy/issues/1233). And yes, I still get that issue as well, but I've realised it doesn't really affect my video outputs, so I don't mind it.
I would say review #1233's thread, and then consider opening a new issue if that thread doesn't really address the issue. Happy to back you on that thread too.
Seems like you're a contributor, so couldn't you PR to help fix this?

**Comment by ganeshmohane-aisolo** [comment]
Facing same issue of list out of range

Notice the difference between two clips is minute and this error only being thrown to this no. only 8.32 and 8.3 


### moviepy version - 1.0.3
Quick Reproducable code
```python
import moviepy.editor as mp

# Create two clips with tiny duration difference
clip1 = mp.ColorClip(size=(640,360), color=(255,0,0), duration=8.32).set_fps(30)
clip2 = mp.ColorClip(size=(640,360), color=(0,255,0), duration=8.3).set_fps(30)

print(f"Clip1: {clip1.duration}s, Clip2: {clip2.duration}s")

diff = clip1.duration-clip2.duration

print("Difference", diff, 'roundof:',round(diff,2))

loops = int(clip1.duration / clip2.duration + 1)
print(f"Loops needed: {loops}")

try:
    concatenated = mp.concatenate_videoclips([clip2] * loops)
    frames = list(concatenated.iter_frames(fps=30))
    print(f"SUCCESS: {len(frames)} frames extracted")
except Exception as e:
    print(f"FAILED: {e}")
```
